baseURL: 'http://localhost:1313/'
languageCode: en-us
title: craftycoder.com
theme: syna
outputs:
  home:
    - HTML
    - JSON
frontmatter:
  date:
    - date
    - lastmod
  lastmod:
    - lastmod
    - ':git'
    - date
markup:
  goldmark:
    renderer:
      unsafe: true
